#!/bin/sh

echo_usage() {
	echo
	echo Usage: $0 aliasName_for_cert path_to_fileCertRequest
	echo
}

if [ $# -ne 2 ]; then

	echo_usage
	exit 1
fi
PRG="$0"

while [ -h "${PRG}" ]; do
  ls=`ls -ld "${PRG}"`
  link=`expr "${ls}" : '.*-> \(.*\)$'`
  if expr "${link}" : '.*/.*' > /dev/null; then
    PRG="${link}"
  else
    PRG="`dirname ${PRG}`/${link}"
  fi
done
PRGDIR="`dirname ${PRG}`"
#. "${PRGDIR}"/../../../conf/set_env

echo "#############################################################"
echo
echo "Generate a certificate signing request ($2)  FROM keystore file [MLProxy.ks] using alias $1." 
echo "Be ready to give the PASSWORD for your keystore in [MLService.ks]."
echo "Execution can be stopped using ^C."
echo
echo "#############################################################"
${JAVA_HOME}/bin/keytool -keystore $PRGDIR/../Service/MLProxy.ks -certreq -alias $1 -file $2
