#!/bin/bash

cd `dirname $0`

export CLASSPATH=`../../classpath.sh ../../`:.

if [ $# -eq 1 ]
  then
    `cat ../../../../conf/env.JAVA_HOME`/bin/java org.apache.axis.wsdl.WSDL2Java $1
 else
    `cat ../../../../conf/env.JAVA_HOME`/bin/java org.apache.axis.wsdl.WSDL2Java  "`../../../../conf/MWS.sh`?wsdl"    
fi    
