#!/bin/bash

cd `dirname $0`

export CLASSPATH=`../../classpath.sh ../../`:.

if [ $# -eq 0 ]
  then
    `cat ../../../../conf/env.JAVA_HOME`/bin/java Client "`../../../../conf/MWS.sh`?wsdl"
  else    
    `cat ../../../../conf/env.JAVA_HOME`/bin/java Client $1
fi      
  
    
