#!/bin/sh

PRG="$0"

while [ -h "${PRG}" ]; do
  ls=`ls -ld "${PRG}"`
  link=`expr "${ls}" : '.*-> \(.*\)$'`
  if expr "${link}" : '.*/.*' > /dev/null; then
    PRG="${link}"
  else
    PRG="`dirname ${PRG}`/${link}"
  fi
done

# Get standard environment variables
PRGDIR="`dirname ${PRG}`"
. "${PRGDIR}"/../conf/set_env
CERTS_PATH="$PRGDIR/../Services/LU_reggie/persistent/certs"
echo "#############################################################"
echo
echo "Generating keys pair TO keystore $CERTS_PATH/lus.keystore" 
echo "Be ready to give the PASSWORD for your keystore !!"
echo "ATTENTION! If the keystore file doesn't exists it will be created!!!"
echo "ATTENTION! The password provided, in this case, will become the password for your keystore."
echo "Execution can be stopped using ^C."
echo
echo "#############################################################"

if [ -e $CERTS_PATH/lus.keystore ];
then
    echo -e "Keystore already initialized ! \nRemove the file $CERTS_PATH/lus.keystore and try again."
    exit 1    
fi


read -s -e -p "PASSWORD to protect your keystore:" pass
echo -e "\nGenerating key-pair ....\n"
${JAVA_HOME}/bin/keytool -genkey -keystore $CERTS_PATH/lus.keystore -alias local_lus -storepass $pass -keypass $pass -validity 1784
ret=$?
if [ $ret -ne 0 ]; then
    exit 1;
fi

echo $pass > $CERTS_PATH/lus.password
chmod 600 $CERTS_PATH/lus.password $CERTS_PATH/lus.keystore

echo "Done."
